language: scala
before_script: ./make_credentials.sh
script: sbt test

env:
  global:
    - secure: "d/JlvgJ3sSkniy/JrvtOMuJ7RUR3JJOD0XaB934k4ftgOOURMjTnY5Z5ZHsBpRPT6bacCCaTpHgyrj/yBZ2zQhZShFOauVZZS5Jm1cvGbBQ2G9vYUcqBiFgxrndiWxOFL6/8qqMZ8WU2lJ8T1nt2+qV1GFnbIom9vd5bLgtqpnA="
    - secure: "x/2S/nxHtDqdg73nXn/elTrYdr5kkEEWn9lowdAJXm1Abw5+fRg0NilEzE6clz0SVENgE2gxDUI/E1lIzaA6D8hIZQzm4tZPOaSsseMpPr83qheDbd6xz2AX11KtAK+0BrogWehrZzjSgVHbpBQWQSZzM1r6XrW2XqCkx8XQ1L8="

# Publish to Sonatype if building master and trigger builds
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && sbt publish"
