language: scala
before_script: ./make_credentials.sh
script: sbt test

env:
  global:
    - secure: "Vmo4gJ1OUV07jK0i8SkdlAV4ozMEDsVTPKJn+p/owP8FXYIBAjiGUVTWaMhAeED/dUL8mkY0B2i8WSeuUwTykwr6dzzgcPAdsOlLVgYKep3DK9qRvKveSfA/oVG8lD3Iq2hwTe0IOATmYD727Idm1/tI33SdaAFSUx5iKHeGlXY="
    - secure: "iis3IlKOzikFaaJkA4tyEStV6Gdz75p3nYUg8H7LKx3GoK7YPuDdqUPkVMw4hWk6Q/snr3MleYzScaRpkhLcGmw4XOhHdZlT2NzbKr8utEmxGTZ7N0NLoC36mt/WFGhwLDDVSFssc3a0KcUxzDPBbvnOLXYbbYlim0aGi04Mvj4="

# Publish to Sonatype if building master and trigger builds
after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && sbt publish"
